# .github/workflows/ci-validation.yml
name: Docker Build + Validation

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        run: |
          docker build -t massnet-dda:latest . -f Dockerfile_cuda11

      - name: Create data directory
        run: mkdir -p ./data

      - name: Download model file
        run: |
          curl -L -o ./data/XuanjiNovo_100M_massnet.ckpt https://huggingface.co/Wyattz23/XuanjiNovo/resolve/main/XuanjiNovo_100M_massnet.ckpt

      - name: Check model file
        run: |
          if [ ! -f "./data/XuanjiNovo_100M_massnet.ckpt" ]; then
            echo "Model file not found!"
            exit 1
          fi

      - name: Download test file
        run: |
          curl -L -o ./data/bacillus.10k.mgf https://huggingface.co/Wyattz23/XuanjiNovo/resolve/main/bacillus.10k.mgf
      - name: Check test file
        run: |
          if [ ! -f "./data/bacillus.10k.mgf" ]; then
            echo "Test file not found!"
            exit 1
           fi

      - name: Run container for validation
        run: |
          docker run --rm \
            -v "./data:/data" \
            massnet-dda:latest \
            --mode=eval \
            --peak_path=/data/bacillus.10k.mgf \
            --model=/data/XuanjiNovo_100M_massnet.ckpt \
            --output=/data/output
